---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kiam-agent-tls
  namespace: kube-system
spec:
  commonName: Kiam Agent
  keySize: 2048
  keyAlgorithm: rsa
  subject:
    countries:
    - UK
    organizationalUnits:
    - WWW
    localities:
    - London
    provinces:
    - London
  organization: 
  - Uswitch
  duration: 8760h
  renewBefore: 720h
  privateKey:
    rotationPolicy: Always
  secretName: kiam-agent-tls
  issuerRef:
    name: kiam
